apply plugin: 'com.android.application'

android {
    namespace "com.angelstudio.angelskitchen"

    compileSdkVersion 35
    defaultConfig {
        applicationId "com.angelstudio.angelskitchen"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 4
        versionName "3.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    dataBinding {
        enabled = true
    }

}

dependencies {
    def retrofitVersion = '2.9.0'
    def lifecycle_version = "2.2.0"
    def supportVersion = "28.0.0"
    def glideVersion = "4.9.0"
    def nav_version = "2.9.3"
    def dagger_version = "2.28.3"
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    //retrofit
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    // Retrofit gson converter
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    // ViewModel and LiveData
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
     // CardViews
    implementation 'androidx.cardview:cardview:1.0.0'
    // RecyclerViews
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    // Design Support
    implementation 'com.google.android.material:material:1.12.0'
    // Glide
    implementation "com.github.bumptech.glide:glide:$glideVersion"
    annotationProcessor "com.github.bumptech.glide:compiler:$glideVersion"
    // Circle ImageView
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    //Navigation
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"
    //youtube video player
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:12.1.2'
    //grid layout
    implementation 'androidx.gridlayout:gridlayout:1.1.0'

    //circular image view
    implementation 'de.hdodenhof:circleimageview:3.0.0'

    implementation "androidx.fragment:fragment:1.8.9"


    androidTestImplementation 'androidx.test:rules:1.7.0'

    implementation "com.google.dagger:dagger:$dagger_version"

}
